return {
    'catppuccin/nvim',
    name = 'catppuccin',
    build = ':CatppuccinCompile',
    lazy = false,
    enabled = true,
    priority = 1000,
    opts = {
        flavour = 'mocha',
        transparent_background = true,
        styles = {
            comments     = { 'italic' },
            properties   = { 'italic' },
            functions    = { 'italic', 'bold' },
            keywords     = { 'italic' },
            operators    = { 'bold' },
            conditionals = { 'bold' },
            loops        = { 'bold' },
            booleans     = { 'bold', 'italic' },
            types        = { 'bold' },
        },
        color_overrides = {
            crust = '#0000000',
            mantle = '#0000000',
            base = '#0000000',
        },
        integrations = {
            cmp = true,
            dashboard = false,
            gitsigns = true,
            leap = true,
            lsp_trouble = true,
            markdown = true,
            notify = true,
            nvimtree = true,
            telescope = true,
            treesitter = true,
            treesitter_context = false,
            which_key = true,
            dap = {
                enabled = true,
                enable_ui = true,
            },
            indent_blankline = {
                enabled = true,
                colored_indent_levels = false,
            },
            native_lsp = {
                underlines = {
                    errors      = { 'undercurl' },
                    hints       = { 'undercurl' },
                    warnings    = { 'undercurl' },
                    information = { 'undercurl' },
                },
            },
            noice = true,
            navic = {
                enabled = true,
                custom_bg = 'NONE',
            },
            lsp_saga = true,
            mason = true,
            ts_rainbow2 = true
        },
        highlight_overrides = {
            mocha = function(cp)
                return {
                    NormalFloat = { fg = cp.text, bg = cp.none },
                    NvimTreeNormal = { bg = cp.none },
                    CmpBorder = { fg = cp.surface2 },
                    Pmenu = { bg = cp.none },
                    NoiceCmdlineIcon = { fg = cp.sky, style = { 'bold' } },
                    -- TelescopeBorder = { link = "FloatBorder" },

                    Keyword = { fg = cp.pink },
                    Type = { fg = cp.blue },
                    Typedef = { fg = cp.yellow },
                    StorageClass = { fg = cp.red, style = { 'italic' } },
                    ['@defaultLibrary'] = { link = '@function.builtin' },
                    ['@documentation'] = { style = { 'bold' } },
                    ['@deprecated'] = { style = { 'strikethrough' } },
                    ['@static'] = { fg = cp.green, style = { 'bold' } },
                    ['@field'] = { fg = cp.rosewater },
                    ['@property'] = { fg = cp.yellow },
                    ['@macro'] = { fg = cp.teal, style = {} },
                    ['@include'] = { fg = cp.teal },
                    ['@operator'] = { fg = cp.sky },
                    ['@keyword.operator'] = { fg = cp.sky },
                    ['@punctuation.special'] = { fg = cp.maroon },
                    -- ["@float"] = { fg = cp.peach },
                    -- ["@number"] = { fg = cp.peach },
                    -- ["@boolean"] = { fg = cp.peach },

                    ['@constructor'] = { fg = cp.lavender },
                    -- ["@constant"] = { fg = cp.peach },
                    -- ["@conditional"] = { fg = cp.mauve },
                    -- ["@repeat"] = { fg = cp.mauve },
                    ['@exception'] = { fg = cp.peach },
                    ['@constant.builtin'] = { fg = cp.lavender },
                    ['@function.builtin'] = { fg = cp.peach, style = { 'italic' } },
                    ['@type.builtin'] = { fg = cp.yellow, style = { 'italic' } },
                    ['@variable.builtin'] = { fg = cp.red, style = { 'italic' } },
                    -- ["@function"] = { fg = cp.blue },
                    ['@function.macro'] = { fg = cp.red, style = {} },
                    ['@parameter'] = { fg = cp.rosewater },
                    ['@keyword.function'] = { fg = cp.maroon },
                    ['@keyword'] = { fg = cp.red, style = { 'italic' } },
                    ['@keyword.return'] = { fg = cp.pink, style = {} },
                    -- ["@text.note"] = { fg = cp.base, bg = cp.blue },
                    -- ["@text.warning"] = { fg = cp.base, bg = cp.yellow },
                    -- ["@text.danger"] = { fg = cp.base, bg = cp.red },
                    -- ["@constant.macro"] = { fg = cp.mauve },

                    -- ["@label"] = { fg = cp.blue },
                    ['@method'] = { style = { 'italic' } },
                    ['@namespace'] = { fg = cp.rosewater, style = {} },
                    ['@punctuation.delimiter'] = { fg = cp.teal },
                    ['@punctuation.bracket'] = { fg = cp.overlay2 },
                    -- ["@string"] = { fg = cp.green },
                    -- ["@string.regex"] = { fg = cp.peach },
                    -- ["@type"] = { fg = cp.yellow },
                    ['@variable'] = { fg = cp.text },
                    ['@tag.attribute'] = { fg = cp.mauve, style = { 'italic' } },
                    ['@tag'] = { fg = cp.peach },
                    ['@tag.delimiter'] = { fg = cp.maroon },
                    ['@text'] = { fg = cp.text },
                    -- ["@text.uri"] = { fg = cp.rosewater, style = { "italic", "underline" } },
                    -- ["@text.literal"] = { fg = cp.teal, style = { "italic" } },
                    -- ["@text.reference"] = { fg = cp.lavender, style = { "bold" } },
                    -- ["@text.title"] = { fg = cp.blue, style = { "bold" } },
                    -- ["@text.emphasis"] = { fg = cp.maroon, style = { "italic" } },
                    -- ["@text.strong"] = { fg = cp.maroon, style = { "bold" } },
                    -- ["@string.escape"] = { fg = cp.pink },

                    -- ["@property.toml"] = { fg = cp.blue },
                    -- ["@field.yaml"] = { fg = cp.blue },

                    -- ["@label.json"] = { fg = cp.blue },

                    ['@function.builtin.bash'] = { fg = cp.red, style = { 'italic' } },
                    ['@parameter.bash'] = { fg = cp.yellow, style = { 'italic' } },
                    ['@field.lua'] = { fg = cp.lavender },
                    ['@constructor.lua'] = { fg = cp.flamingo },
                    ['@constant.java'] = { fg = cp.teal },
                    ['@property.typescript'] = { fg = cp.lavender, style = { 'italic' } },
                    -- ["@constructor.typescript"] = { fg = cp.lavender },

                    -- ["@constructor.tsx"] = { fg = cp.lavender },
                    -- ["@tag.attribute.tsx"] = { fg = cp.mauve },

                    ['@type.css'] = { fg = cp.lavender },
                    ['@property.css'] = { fg = cp.yellow, style = { 'italic' } },
                    ['@type.builtin.c'] = { fg = cp.yellow, style = {} },
                    ['@property.cpp'] = { fg = cp.text },
                    ['@type.builtin.cpp'] = { fg = cp.yellow, style = {} },
                    -- ["@symbol"] = { fg = cp.flamingo },
                }
            end,
        },
        custom_highlights = {
            LspFloatWinNormal       = { bg = 'NONE' },
            TreesitterContextBottom = { underline = true, sp = '#6E6C7E', }
        },
    },
    config = function(_, opts)
        require('catppuccin').setup(opts)
        vim.cmd.colorscheme('catppuccin')
    end
}
