require('util').vim_opts {
    g = {
        colorscheme             = 'catppuccin',
        mapleader               = ' ',
        loaded_node_provider    = false,
        loaded_perl_provider    = false,
        loaded_python3_provider = false,
        loaded_ruby_provider    = false,
    },
    opt = {
        termguicolors  = true,
        guifont        = {
            'CaskaydiaCove NF',
            'nonicons:h12',
        },
        mouse          = 'a',
        laststatus     = 3,
        cmdheight      = 0,
        shada          = '',
        wrap           = false,
        undofile       = true,
        updatetime     = 50,
        timeoutlen     = 250,
        showmode       = false,
        number         = true,
        relativenumber = true,
        signcolumn     = 'number',
        cindent        = true,
        softtabstop    = 4,
        tabstop        = 4,
        shiftwidth     = 4,
        expandtab      = true,
        fillchars      = {
            fold = ' ',
            eob = ' ',
            foldsep = ' ',
        },
        -- listchars      = {
        --     tab = '» ',
        --     trail = '·',
        --     extends = '<',
        --     precedes = '>',
        --     conceal = '┊',
        --     nbsp = '␣',
        -- },
        preserveindent = true,
        foldlevel      = 99,
        clipboard      = 'unnamedplus',
        scrolloff      = 8,
        splitbelow     = true,
        splitright     = true,
        spelloptions   = 'camel,noplainbuffer',
        mousemoveevent = true,
        splitkeep      = 'screen',
        winblend       = 10,
        -- pumblend       = 10
    }
}
